export const Images = {
    ic_netInfo: require('../../res/images/netConnection.png'),
    ic_camera: require('../../res/images/camera.png'),
    ic_back: require('../../res/images/back.png'),
    ic_box: require('../../res/images/box.png'),
    img_splash_portrait: require('../../res/images/splash_portrait.png'),
    img_splash_landscape: require('../../res/images/splash_landscape.png'),
    ic_settings: require('../../res/images/settings.png'),
    ic_deleteback: require('../../res/images/deleteback.png'),
    ic_done: require('../../res/images/done.png'),

    img_splash_screen: require('../../res/images/splash_screen.png'),
    ic_sub_logo_1: require('../../res/images/sub_logo_1.png'),
    ic_sub_logo_2: require('../../res/images/sub_logo_2.png'),
    ic_logo: require('../../res/images/logo.png'),
    ic_text_icon: require('../../res/images/text_icon.png'),
    ic_logo2: require('../../res/images/water.png'),
    ic_menu: require('../../res/images/menu.png'),
    img_sidebar_header: require('../../res/images/sidebar_header.png'),
    ic_phone: require('../../res/images/phone.png'),
    ic_email: require('../../res/images/email.png'),
    ic_home_bg: require('../../res/images/home_bg.png'),
}
